### ISSUE TITLE
Frontend Task - Develop Badge Dashboard

### ISSUE THREAD

**Issue by Okm165** [visoftsolutions/ksox#2]
#### Introduction
Users on KSOX Exchange will receive badges for certain actions, we need dashboard to present already gained badges and those that are not yet received.
There are 5 groups of badges more info can be found here: 
[README.md](https://github.com/visoftsolutions/ksox/files/11663364/README.md)

#### Root
ksox/web/@app/dasboard/

#### Task Description
Develop Dashboard component that will present badges themselves in groups they belong to in appealing and informative way.
Each badge is going to have name, short description, progress bar, and avatar / graphic.
Badge can be in two states "gained"  (progressbar 100% and highlighted) and "not gained"  (progresbarr at X%)
Design frontend components using mainly color pallete from ksox/web/@app/dashboard/tailwind.config.cjs
Dashboard needs to be responsive, it has to present well on both desktop and mobile. For responsive design use only tailwindCSS media query tags.

#### Files
Progress bar component pattern can be found here: 
ksox/web/@app/exchange-landing/src/components/Token/ProgressBar.tsx

**Comment by kgrybos** [comment]
I would like to claim this task
