### ISSUE TITLE
Frontend Task - Develop User Panel

### ISSUE THREAD

**Issue by Okm165** [visoftsolutions/ksox#3]
Introduction
Users on KSOX Exchange will receive badges for certain actions, we need user panel to present already gained badges.
There are 5 groups of badges more info can be found here:
[README.md](https://github.com/visoftsolutions/ksox/files/11663364/README.md)

Root
ksox/web/@app/dasboard/

Task Description
Develop User Panel component that will present basic user info (user name, user's avatar) and received badges.
Panel should take less than half of the viewport's height.
Design frontend components using mainly color pallete from ksox/web/@app/dashboard/tailwind.config.cjs
Dashboard needs to be responsive, it has to present well on both desktop and mobile. For responsive design use only tailwindCSS media query tags.

**Comment by Fifus17** [comment]
Claim'uje!
