### ISSUE TITLE
Frontend Task - Develop Stack Based Popup Notification Component

### ISSUE THREAD

**Issue by Okm165** [visoftsolutions/ksox#6]
Introduction
There is need for component that we can show notifications with. This component is placed in bottom left corner. It works like FIFO queue. Items are auto-removed after constant amount of time.

Root
ksox/web/@app/dasboard/

Task Description
Most recent notification is displayed at the bottom-most position of the component. Notifications are removed from the 
top-most position when the have been displayed for some time. Notifications are tiles on this stack.
Tile should be of simple design should handle arbitrary children component.

**Comment by Fifus17** [comment]
Claim
