### ISSUE TITLE
Upgrade Badge Storage to PostgreSQL

### ISSUE THREAD

**Issue by Okm165** [visoftsolutions/ksox#8]
### Description
The current badge storage mechanism in the engagement engine has limitations that hinder the flexibility of managing badges. The badges are currently stored in the code, preventing easy addition, modification, or removal of badges while the service is running. To overcome these limitations and improve the badge management functionality, we need to upgrade the badge storage to PostgreSQL.

Analyze the current engagement engine and the code responsible for badge storage: `server/engagement/src/engagement_engine/badges`

### Proposed Solution
The proposed solution is to store the badges' metadata in a PostgreSQL database. This upgrade will allow us to add new badges, modify descriptions, names, and values of existing badges without having to make changes to the code. The goal is to preserve the current engagement functionality while enhancing the badge management capabilities.

### Additional Information
Before proceeding with the implementation, please reach out to me to clarify any additional details or requirements. It is crucial to maintain the current code conventions and adhere to good practices throughout the upgrade process.

**Note:** If you need assistance or have any questions during the implementation, please don't hesitate to ask for support.

**Comment by amajewski505** [comment]
claim
